name: ai4bharat
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.10.19
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - anyio==4.12.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.5.0
      - dill==0.4.0
      - exceptiongroup==1.3.1
      - filelock==3.20.3
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - idna==3.11
      - jinja2==3.1.6
      - jiwer==4.0.0
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - netron==8.8.3
      - networkx==3.4.2
      - numpy==2.2.6
      - onnx==1.20.1
      - onnx-graphsurgeon==0.5.8
      - onnxruntime==1.23.2
      - packaging==26.0
      - pandas==2.3.3
      - pillow==12.1.0
      - propcache==0.4.1
      - protobuf==6.33.4
      - pyarrow==23.0.0
      - pycparser==3.0
      - pyparsing==3.3.2
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - rapidfuzz==3.14.3
      - regex==2026.1.15
      - requests==2.32.5
      - safetensors==0.7.0
      - six==1.17.0
      - soundfile==0.13.1
      - sympy==1.14.0
      - tokenizers==0.22.2
      - torch==2.10.0
      - torchaudio==2.10.0
      - tqdm==4.67.1
      - transformers==4.57.6
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.3
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: C:\Users\apran\anaconda3\envs\ai4bharat
